(Don't worry about this starter text.  I'll share the file after class.)

# Friday Week 0, Math 10, Fall 2021
Topics:
* lists and related data structures in Python
* Indexing and slicing
* for loops

There are a huge number of data types in Python, both built-in data types (like list) and data types that come from an external library (like NumPy arrays).  Often data types can appear quite similar.  Here is an example of five data types which all share some common properties:
* list
* set
* tuple
* range
* NumPy array

It is important to recognize how these are similar and different, and what advantages/disadvantages some of them have over others.

## lists

In [1]:
my_list = [3,1,4,1,5]

In [2]:
type(my_list)

list

In [3]:
len(my_list)

5

In [4]:
# indexing
my_list[2]

4

In [5]:
# slicing
my_list[2:]

[4, 1, 5]

In [6]:
my_list[2:4]

[4, 1]

In [7]:
my_list

[3, 1, 4, 1, 5]

In [8]:
my_list[2] = "hello Math 10"

In [9]:
my_list

[3, 1, 'hello Math 10', 1, 5]

In [10]:
# this changes my_list
my_list.append(4)

In [11]:
my_list

[3, 1, 'hello Math 10', 1, 5, 4]

In [12]:
new_list = [3,1,4,1]

In [13]:
# this doesn't change new_list.  It makes a different list
sorted(new_list)

[1, 1, 3, 4]

In [14]:
new_list

[3, 1, 4, 1]

In [15]:
# to change the original
new_list = sorted(new_list)

In [16]:
new_list

[1, 1, 3, 4]

In [17]:
new_list.extend([3,1,4])

In [18]:
new_list

[1, 1, 3, 4, 3, 1, 4]

In [19]:
new_list.append([3,1,4])

In [20]:
new_list

[1, 1, 3, 4, 3, 1, 4, [3, 1, 4]]

In [21]:
new_list[-1]

[3, 1, 4]

In [22]:
type(new_list[-1])

list

In [23]:
type(new_list[-2])

int

## sets

In [25]:
my_list

[3, 1, 'hello Math 10', 1, 5, 4]

In [26]:
my_set = set(my_list)

In [27]:
my_set

{1, 3, 4, 5, 'hello Math 10'}

In [33]:
# repetitions disappeared.  (Just like in math sets.)
set([3,1,4,1,-10,5])

{-10, 1, 3, 4, 5}

In [34]:
# sets don't have a notion of order, so taking the 2nd element
# doesn't make sense
my_set[2]

TypeError: 'set' object is not subscriptable

In [35]:
len(my_set)

5

In [36]:
my_set

{1, 3, 4, 5, 'hello Math 10'}

In [37]:
# by hand way to make a set:
{2,10,4}

{2, 4, 10}

In [38]:
type(my_set)

set

## tuples

In [39]:
my_tuple = (3,1,4,1)

In [40]:
my_tuple

(3, 1, 4, 1)

In [41]:
my_tuple[1:3]

(1, 4)

In [42]:
len(my_tuple)

4

In [44]:
# you should not change a tuple after you've made it.
print("hi")
my_tuple[2] = 10
print("hello")

hi


TypeError: 'tuple' object does not support item assignment

In [45]:
my_tuple.append(4)

AttributeError: 'tuple' object has no attribute 'append'

In [46]:
# Why would we ever use tuples?
# tuples can go in a set, and lists can't
{5,10,my_tuple}

{(3, 1, 4, 1), 10, 5}

In [48]:
{5,10,my_list}

TypeError: unhashable type: 'list'

## range

In [49]:
my_range = range(0,100,3)

In [50]:
my_range

range(0, 100, 3)

In [51]:
list(my_range)

[0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 24,
 27,
 30,
 33,
 36,
 39,
 42,
 45,
 48,
 51,
 54,
 57,
 60,
 63,
 66,
 69,
 72,
 75,
 78,
 81,
 84,
 87,
 90,
 93,
 96,
 99]

In [52]:
list(range(0,10,1))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [54]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [53]:
range(0,10,0.5)

TypeError: 'float' object cannot be interpreted as an integer

In [56]:
## Aside
2^6

4

In [57]:
2**6

64

In [58]:
my_range = range(0,10**40,3)

In [59]:
list(my_range)

OverflowError: Python int too large to convert to C ssize_t

## NumPy arrays

In [60]:
import numpy as np

In [62]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [64]:
my_tuple

(3, 1, 4, 1)

In [66]:
A = np.array(my_tuple)

In [67]:
A

array([3, 1, 4, 1])

In [68]:
A[1:]

array([1, 4, 1])

In [69]:
np.cos(A)

array([-0.9899925 ,  0.54030231, -0.65364362,  0.54030231])