# Introduction to TensorFlow
I found it very difficult to install on my M1 Mac computer.  Maybe it will work better for you.

On most computers (including the lab computers), it should be enough to go to 
* Anaconda Navigator -> Environments -> Uninstalled -> `tensorflow`
and then click *Apply*.  It may take about 5 minutes.

Another option is to open a terminal and type `pip install tensorflow`.

If you can't get it installed on your computer, an alternative is to try running this notebook in [Google Colab](https://colab.research.google.com/) or on a website called [Deepnote](https://deepnote.com/).  I personally prefer Deepnote, but Google Colab is more famous and more optimized for TensorFlow.

If you get tired of the TensorFlow warning messages, you can hide most of them with the following code.  It must be run before you import tensorflow.  If you change 3 to 2 or 1 or 0, there will be more warning messages (with 0 having all the warning messages).  [Source](https://stackoverflow.com/questions/35911252/disable-tensorflow-debugging-information)

```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
```

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras

Init Plugin
Init Graph Optimizer
Init Kernel


In [9]:
model = keras.Sequential(
    [
        keras.layers.InputLayer(input_shape = (2,)),
        keras.layers.Dense(1,activation="sigmoid")
    ]
)

In [3]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [10]:
model.get_weights()

[array([[ 1.0675725],
        [-0.8307821]], dtype=float32),
 array([0.], dtype=float32)]

In [11]:
# "mse"
model.compile(loss="binary_crossentropy",
              optimizer="sgd",metrics=["accuracy"])

In [12]:
X = [[0,0],
    [1,0],
    [0,1],
    [1,1]]

In [13]:
y = [0,1,1,1]

In [14]:
model.fit(X,y)

1/1 [==============================] - 0s 123ms/step - loss: 0.6907 - accuracy: 0.7500


2021-11-17 12:41:27.633026: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


In [15]:
model.fit(X,y,epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 8ms/step - loss: 0.6891 - accuracy: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 7ms/step - loss: 0.6875 - accuracy: 0.5000
Epoch 3/100
1/1 [==============================] - 0s 5ms/step - loss: 0.6859 - accuracy: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 5ms/step - loss: 0.6843 - accuracy: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 7ms/step - loss: 0.6828 - accuracy: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 5ms/step - loss: 0.6812 - accuracy: 0.5000
Epoch 7/100
1/1 [==============================] - 0s 5ms/step - loss: 0.6797 - accuracy: 0.5000
Epoch 8/100
1/1 [==============================] - 0s 7ms/step - loss: 0.6781 - accuracy: 0.5000
Epoch 9/100
1/1 [==============================] - 0s 5ms/step - loss: 0.6766 - accuracy: 0.5000
Epoch 10/100
1/1 [==============================] - 0s 5ms/step - loss: 0.6751 - accuracy: 0.5000
Epoch 11/100
1/1 [===========

In [16]:
model.get_weights()

[array([[ 1.217262  ],
        [-0.57473016]], dtype=float32),
 array([0.18040945], dtype=float32)]

In [18]:
model.predict([[0,0]])

2021-11-17 12:44:21.663560: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


array([[0.54498047]], dtype=float32)

In [21]:
model.fit(X,y,epochs=1000,verbose=False)

In [22]:
model.predict([[0,0]])

array([[0.5626659]], dtype=float32)