# Midterm Review

In [1]:
import numpy as np
import pandas as pd
import altair as alt
from sklearn.linear_model import LinearRegression

rng = np.random.default_rng()

In [3]:
A = rng.integers(0,10,size=(1,5))
A

array([[8, 0, 5, 1, 8]])

In [4]:
A = rng.integers(0,10,size=(5))
A

array([7, 9, 7, 0, 6])

In [5]:
A = rng.integers(0,10,size=(2,5))
A

array([[6, 8, 9, 5, 5],
       [3, 9, 8, 0, 0]])

In [12]:
A = rng.integers(0,10,size=(5,10))

In [13]:
# How many columns in A contain a 6
B = (A == 6)

In [14]:
type(B)

numpy.ndarray

In [15]:
B.sum(axis=0).shape

(10,)

In [17]:
A

array([[6, 5, 1, 6, 6, 9, 8, 6, 6, 9],
       [0, 6, 5, 8, 7, 7, 9, 7, 6, 9],
       [5, 6, 2, 2, 7, 6, 1, 8, 3, 7],
       [3, 2, 3, 7, 2, 2, 5, 6, 3, 9],
       [6, 2, 7, 6, 5, 6, 0, 7, 1, 6]])

In [18]:
B = (A == 6)

In [19]:
B[2,0:4]

array([False,  True, False, False])

In [21]:
B[2,1::2]

array([ True, False,  True, False, False])

In [23]:
C = (B.sum(axis=0))
C

array([2, 2, 0, 2, 1, 2, 0, 2, 2, 1])

In [24]:
(C > 0).sum()

8

In [25]:
A

array([[6, 5, 1, 6, 6, 9, 8, 6, 6, 9],
       [0, 6, 5, 8, 7, 7, 9, 7, 6, 9],
       [5, 6, 2, 2, 7, 6, 1, 8, 3, 7],
       [3, 2, 3, 7, 2, 2, 5, 6, 3, 9],
       [6, 2, 7, 6, 5, 6, 0, 7, 1, 6]])

In [27]:
df = pd.DataFrame(A)
df

0  1  2  3  4  5  6  7  8  9
0  6  5  1  6  6  9  8  6  6  9
1  0  6  5  8  7  7  9  7  6  9
2  5  6  2  2  7  6  1  8  3  7
3  3  2  3  7  2  2  5  6  3  9
4  6  2  7  6  5  6  0  7  1  6

In [28]:
def has6(c):
    b = (6 in c)
    return b

In [36]:
def has6(c):
    return (6 in list(c))

In [30]:
has6([2,5,6,3])

True

In [32]:
df

0  1  2  3  4  5  6  7  8  9
0  6  5  1  6  6  9  8  6  6  9
1  0  6  5  8  7  7  9  7  6  9
2  5  6  2  2  7  6  1  8  3  7
3  3  2  3  7  2  2  5  6  3  9
4  6  2  7  6  5  6  0  7  1  6

In [37]:
df.apply(has6,axis=0)

0     True
1     True
2    False
3     True
4     True
5     True
6    False
7     True
8     True
9     True
dtype: bool

In [40]:
df == 6

0      1      2      3      4      5      6      7      8      9
0   True  False  False   True   True  False  False   True   True  False
1  False   True  False  False  False  False  False  False   True  False
2  False   True  False  False  False   True  False  False  False  False
3  False  False  False  False  False  False  False   True  False  False
4   True  False  False   True  False   True  False  False  False   True

In [39]:
(df == 6).any(axis=0)

0     True
1     True
2    False
3     True
4     True
5     True
6    False
7     True
8     True
9     True
dtype: bool

In [41]:
(df == 6).any(axis=1)

0    True
1    True
2    True
3    True
4    True
dtype: bool

In [42]:
df

0  1  2  3  4  5  6  7  8  9
0  6  5  1  6  6  9  8  6  6  9
1  0  6  5  8  7  7  9  7  6  9
2  5  6  2  2  7  6  1  8  3  7
3  3  2  3  7  2  2  5  6  3  9
4  6  2  7  6  5  6  0  7  1  6

In [48]:
help(df.apply)

Help on method apply in module pandas.core.frame:

apply(func: 'AggFuncType', axis: 'Axis' = 0, raw: 'bool' = False, result_type=None, args=(), **kwargs) method of pandas.core.frame.DataFrame instance
    Apply a function along an axis of the DataFrame.
    
    Objects passed to the function are Series objects whose index is
    either the DataFrame's index (``axis=0``) or the DataFrame's columns
    (``axis=1``). By default (``result_type=None``), the final return type
    is inferred from the return type of the applied function. Otherwise,
    it depends on the `result_type` argument.
    
    Parameters
    ----------
    func : function
        Function to apply to each column or row.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Axis along which the function is applied:
    
        * 0 or 'index': apply function to each column.
        * 1 or 'columns': apply function to each row.
    
    raw : bool, default False
        Determines if row or column is passed as 

In [47]:
df.apply(lambda row: row[2]-row[3], axis=1)

0   -5
1   -3
2    0
3   -4
4    1
dtype: int64

In [50]:
df

0  1  2  3  4  5  6  7  8  9
0  6  5  1  6  6  9  8  6  6  9
1  0  6  5  8  7  7  9  7  6  9
2  5  6  2  2  7  6  1  8  3  7
3  3  2  3  7  2  2  5  6  3  9
4  6  2  7  6  5  6  0  7  1  6

In [52]:
df.max(axis=0)

0    6
1    6
2    7
3    8
4    7
5    9
6    9
7    8
8    6
9    9
dtype: int64

In [51]:
df.apply(max, axis=0)

0    6
1    6
2    7
3    8
4    7
5    9
6    9
7    8
8    6
9    9
dtype: int64

In [49]:
df.apply(lambda col: col[2]-col[3], axis=0)

0    2
1    4
2   -1
3   -5
4    5
5    4
6   -4
7    2
8    0
9   -2
dtype: int64

In [46]:
df.apply(len, axis=1)

0    10
1    10
2    10
3    10
4    10
dtype: int64

In [44]:
df.applymap(lambda x: 0 if x < 5 else 1000)

0     1     2     3     4     5     6     7     8     9
0  1000  1000     0  1000  1000  1000  1000  1000  1000  1000
1     0  1000  1000  1000  1000  1000  1000  1000  1000  1000
2  1000  1000     0     0  1000  1000     0  1000     0  1000
3     0     0     0  1000     0     0  1000  1000     0  1000
4  1000     0  1000  1000  1000  1000     0  1000     0  1000

In [43]:
df.applymap(lambda x: x+10)

0   1   2   3   4   5   6   7   8   9
0  16  15  11  16  16  19  18  16  16  19
1  10  16  15  18  17  17  19  17  16  19
2  15  16  12  12  17  16  11  18  13  17
3  13  12  13  17  12  12  15  16  13  19
4  16  12  17  16  15  16  10  17  11  16

In [60]:
s = pd.Series({"a":10,"b":10,"c":3})
s

a    10
b    10
c     3
dtype: int64

In [61]:
t = pd.Series({"a":1,"b":1,"c":2})
t

a    1
b    1
c    2
dtype: int64

In [58]:
s.max()

10

In [59]:
{"a":10,"b":10,"c":3}.max()

AttributeError: 'dict' object has no attribute 'max'

In [55]:
s.map(lambda x: x+3)

a    13
b    13
c     6
dtype: int64

In [56]:
df.map(lambda x: x+3)

AttributeError: 'DataFrame' object has no attribute 'map'

In [54]:
s.applymap(lambda x: x+3)

AttributeError: 'Series' object has no attribute 'applymap'