# Week 1 Friday Lecture

Download the csv file "indexData.csv" from Files->Datasets on Canvas.  Save the file somewhere you can access on the computer.
This "indexData.csv" comes from [here](https://www.kaggle.com/mattiuzc/stock-exchange-data), but I changed the name of the first column so you should use the version on Canvas, not the version on Kaggle.

Goals for today:
* Introduce dictionaries, an important data type.
* Introduce the library pandas (for working with spreadsheet-like data)
* Similarity: both of these involve "named" data entries.

## Aside: listing folder contents in Python
You should skip this section, but you can refer to it if you are trying to navigate and find files from within Jupyter.

In [1]:
import os

In [2]:
os.getcwd()

'/Users/christopherdavis/Dropbox/UCI-Math-10-Davis/Week1'

In [3]:
os.listdir()

['Week 1 - Wednesday Lecture.ipynb',
 'Week 1 - Friday Lecture.ipynb',
 '.ipynb_checkpoints',
 'Week 1 - Monday Worksheet.ipynb']

In [5]:
# On a Windows computer, instead try !dir
!ls

Week 1 - Friday Lecture.ipynb    Week 1 - Wednesday Lecture.ipynb
Week 1 - Monday Worksheet.ipynb


In [19]:
# This means: list all the files (and folders) up one level, in the data folder.
# Might need a backslash instead of a front slash on a different computer.
# This only works if there is a folder called data there.
os.listdir("../data")

['FastFoodRestaurants.csv', 'indexData.csv']

In [18]:
# More robust, but still only works if there is a data folder up one level.
os.listdir(os.path.join("..","data"))

['FastFoodRestaurants.csv', 'indexData.csv']

## Dictionaries

In [1]:
roles = {"chris": "teacher", "yasmeen": "TA", 
         "xingshuo": "LA", "chupeng": "LA"}

In [2]:
type(roles)

dict

In [3]:
roles["yasmeen"]

'TA'

In [4]:
roles[xingshuo]

NameError: name 'xingshuo' is not defined

In [5]:
c = "xingshuo"

In [6]:
roles[c]

'LA'

In [7]:
roles[(3,1)] = 17

In [8]:
roles[[2,5]] = 10

TypeError: unhashable type: 'list'

In [9]:
roles

{'chris': 'teacher',
 'yasmeen': 'TA',
 'xingshuo': 'LA',
 'chupeng': 'LA',
 (3, 1): 17}

In [10]:
roles['chris'] = 'professor'

In [11]:
# Notice that there cannot be repeated keys: there is only one "chris" key
roles

{'chris': 'professor',
 'yasmeen': 'TA',
 'xingshuo': 'LA',
 'chupeng': 'LA',
 (3, 1): 17}

In [12]:
my_list = [3,1,5]

In [13]:
my_list[2] = 10

In [14]:
my_list

[3, 1, 10]

In [15]:
my_list[7] = 0

IndexError: list assignment index out of range

## pandas

In [17]:
import pandas as pd
import numpy as np

In [20]:
A = np.arange(40).reshape((10,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [21]:
A.shape

(10, 4)

In [23]:
np.arange(40).reshape((-1,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [24]:
np.arange(40).reshape((-1,3))

ValueError: cannot reshape array of size 40 into shape (3)

In [25]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [26]:
list(A)

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14, 15]),
 array([16, 17, 18, 19]),
 array([20, 21, 22, 23]),
 array([24, 25, 26, 27]),
 array([28, 29, 30, 31]),
 array([32, 33, 34, 35]),
 array([36, 37, 38, 39])]

In [28]:
df = pd.DataFrame(A)
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19
5  20  21  22  23
6  24  25  26  27
7  28  29  30  31
8  32  33  34  35
9  36  37  38  39

In [29]:
type(df)

pandas.core.frame.DataFrame

In [32]:
df = pd.DataFrame(A,columns=["a","b","e","a"])
df

a   b   e   a
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19
5  20  21  22  23
6  24  25  26  27
7  28  29  30  31
8  32  33  34  35
9  36  37  38  39

In [35]:
list("hi there chris davis")

['h',
 'i',
 ' ',
 't',
 'h',
 'e',
 'r',
 'e',
 ' ',
 'c',
 'h',
 'r',
 'i',
 's',
 ' ',
 'd',
 'a',
 'v',
 'i',
 's']

In [34]:
df = pd.DataFrame(A,columns=list("hi there chris davis"))
df

ValueError: Shape of passed values is (10, 4), indices imply (10, 20)

In [36]:
df = pd.DataFrame(A,columns=list("abcd"))
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19
5  20  21  22  23
6  24  25  26  27
7  28  29  30  31
8  32  33  34  35
9  36  37  38  39

In [39]:
df.index = list("abcdefghij")

In [41]:
df.columns = [10,2,5,8]

In [43]:
df

10  2   5   8 
a   0   1   2   3
b   4   5   6   7
c   8   9  10  11
d  12  13  14  15
e  16  17  18  19
f  20  21  22  23
g  24  25  26  27
h  28  29  30  31
i  32  33  34  35
j  36  37  38  39

In [45]:
s = df[8]
s

a     3
b     7
c    11
d    15
e    19
f    23
g    27
h    31
i    35
j    39
Name: 8, dtype: int64

In [46]:
type(s)

pandas.core.series.Series

In [48]:
s["c"]

11

In [47]:
dict(s)

{'a': 3,
 'b': 7,
 'c': 11,
 'd': 15,
 'e': 19,
 'f': 23,
 'g': 27,
 'h': 31,
 'i': 35,
 'j': 39}

In [49]:
# Your path will be different!
df = pd.read_csv("../data/indexData.csv")

In [50]:
df

Name      Date         Open         High          Low        Close  \
0        NYA  12/31/65   528.690002   528.690002   528.690002   528.690002   
1        NYA    1/3/66   527.210022   527.210022   527.210022   527.210022   
2        NYA    1/4/66   527.840027   527.840027   527.840027   527.840027   
3        NYA    1/5/66   531.119995   531.119995   531.119995   531.119995   
4        NYA    1/6/66   532.070007   532.070007   532.070007   532.070007   
...      ...       ...          ...          ...          ...          ...   
112452  N100   5/27/21  1241.119995  1251.910034  1241.119995  1247.069946   
112453  N100   5/28/21  1249.469971  1259.209961  1249.030029  1256.599976   
112454  N100   5/31/21  1256.079956  1258.880005  1248.140015  1248.930054   
112455  N100    6/1/21  1254.609985  1265.660034  1254.609985  1258.579956   
112456  N100    6/2/21  1258.489990  1263.709961  1258.239990  1263.619995   

          Adj Close       Volume  
0        528.690002          0.0  
1        527.210022          0.0  
2        527.840027          0.0  
3        531.119995          0.0  
4        532.070007          0.0  
...             ...          ...  
112452  1247.069946  379696400.0  
112453  1256.599976  160773400.0  
112454  1248.930054   91173700.0  
112455  1258.579956  155179900.0  
112456  1263.619995  148465000.0  

[112457 rows x 8 columns]

Let's find how many days was the high - low for NYSE bigger than 5% of the open value

In [52]:
# restrict to the NYA rows
df["Name"] == "NYA"

0          True
1          True
2          True
3          True
4          True
          ...  
112452    False
112453    False
112454    False
112455    False
112456    False
Name: Name, Length: 112457, dtype: bool

In [54]:
# syntax: dataframe [ Boolean series]
df_nya = df[df["Name"] == "NYA"]
df_nya

Name      Date          Open          High           Low         Close  \
0      NYA  12/31/65    528.690002    528.690002    528.690002    528.690002   
1      NYA    1/3/66    527.210022    527.210022    527.210022    527.210022   
2      NYA    1/4/66    527.840027    527.840027    527.840027    527.840027   
3      NYA    1/5/66    531.119995    531.119995    531.119995    531.119995   
4      NYA    1/6/66    532.070007    532.070007    532.070007    532.070007   
...    ...       ...           ...           ...           ...           ...   
13943  NYA   5/24/21  16375.000000  16508.519530  16375.000000  16464.689450   
13944  NYA   5/25/21  16464.689450  16525.810550  16375.150390  16390.189450   
13945  NYA   5/26/21  16390.189450  16466.339840  16388.320310  16451.960940   
13946  NYA   5/27/21  16451.960940  16546.359380  16451.960940  16531.949220   
13947  NYA   5/28/21  16531.949220  16588.689450  16531.949220  16555.660160   

          Adj Close        Volume  
0        528.690002  0.000000e+00  
1        527.210022  0.000000e+00  
2        527.840027  0.000000e+00  
3        531.119995  0.000000e+00  
4        532.070007  0.000000e+00  
...             ...           ...  
13943  16464.689450  2.947400e+09  
13944  16390.189450  3.420870e+09  
13945  16451.960940  3.674490e+09  
13946  16531.949220  5.201110e+09  
13947  16555.660160  4.199270e+09  

[13948 rows x 8 columns]

In [55]:
df_nya.shape

(13948, 8)

In [56]:
df_nya["High"]

0          528.690002
1          527.210022
2          527.840027
3          531.119995
4          532.070007
             ...     
13943    16508.519530
13944    16525.810550
13945    16466.339840
13946    16546.359380
13947    16588.689450
Name: High, Length: 13948, dtype: float64

In [57]:
df_nya.High

0          528.690002
1          527.210022
2          527.840027
3          531.119995
4          532.070007
             ...     
13943    16508.519530
13944    16525.810550
13945    16466.339840
13946    16546.359380
13947    16588.689450
Name: High, Length: 13948, dtype: float64

In [58]:
df_nya.columns

Index(['Name', 'Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

In [59]:
df_nya.Adj Close

SyntaxError: invalid syntax (<ipython-input-59-cd4feff498c9>, line 1)

In [60]:
df_nya["Adj Close"]

0          528.690002
1          527.210022
2          527.840027
3          531.119995
4          532.070007
             ...     
13943    16464.689450
13944    16390.189450
13945    16451.960940
13946    16531.949220
13947    16555.660160
Name: Adj Close, Length: 13948, dtype: float64

In [61]:
df_nya["High"] - df_nya["Low"]

0          0.00000
1          0.00000
2          0.00000
3          0.00000
4          0.00000
           ...    
13943    133.51953
13944    150.66016
13945     78.01953
13946     94.39844
13947     56.74023
Length: 13948, dtype: float64

In [62]:
(df_nya["High"] - df_nya["Low"])/df_nya["Open"]

0        0.000000
1        0.000000
2        0.000000
3        0.000000
4        0.000000
           ...   
13943    0.008154
13944    0.009151
13945    0.004760
13946    0.005738
13947    0.003432
Length: 13948, dtype: float64

In [63]:
(df_nya["High"] - df_nya["Low"])/df_nya["Open"] > 0.05

0        False
1        False
2        False
3        False
4        False
         ...  
13943    False
13944    False
13945    False
13946    False
13947    False
Length: 13948, dtype: bool

In [64]:
df_nya[(df_nya["High"] - df_nya["Low"])/df_nya["Open"] > 0.05]

Name     Date         Open          High          Low         Close  \
10586  NYA  1/23/08  8661.059570   8806.099609  8343.620117   8805.679688   
10749  NYA  9/15/08  8091.569824   8091.569824  7680.149902   7680.149902   
10752  NYA  9/18/08  7440.390137   7806.410156  7318.839844   7775.160156   
10753  NYA  9/19/08  7775.169922   8201.240234  7775.169922   8187.129883   
10759  NYA  9/29/08  7890.370117   7890.370117  7167.770020   7204.009766   
...    ...      ...          ...           ...          ...           ...   
13644  NYA  3/17/20  9726.179688  10154.160160  9484.650391  10063.360350   
13645  NYA  3/18/20  9562.490234   9666.570313  8953.599609   9384.599609   
13646  NYA  3/19/20  9313.759766   9622.209961  9048.360352   9461.309570   
13647  NYA  3/20/20  9577.900391   9676.940430  9108.150391   9133.160156   
13650  NYA  3/25/20  9749.799805  10303.900390  9591.740234   9961.379883   

          Adj Close        Volume  
10586   8805.679688  3.241600e+08  
10749   7680.149902  8.279510e+09  
10752   7775.160156  1.008269e+10  
10753   8187.129883  9.387170e+09  
10759   7204.009766  7.305060e+09  
...             ...           ...  
13644  10063.360350  8.358500e+09  
13645   9384.599609  8.755780e+09  
13646   9461.309570  7.946710e+09  
13647   9133.160156  9.044690e+09  
13650   9961.379883  8.285670e+09  

[66 rows x 8 columns]